### PR TITLE
Update to the schedulers and bugfixes

### PR DESCRIPTION
**Pull request by kvyh**
This is an update to #182, I have added a Schedule class and modified both of the existing schedulers to be able to use it. I fixed a number of bugs in the two schedulers and started writing tests for the different parts of the scheduling. The major update is that PriorityScheduler uses a transitioner now. Also included are modifications to the notebooks that give an example of how to use the schedulers, since tutorials have yet to be written.

### CODE REVIEW

**Comment by kvyh** [comment]
@bmorris3 Do I need to add anything more, or can this be merged?

**Comment by bmorris3** [comment]
@kvyh It's going to be essential that lots of docs get written between now and the end of the summer. Before I merge this, would you update the notebooks by putting cells of text in between each cell of code, explaining what you do in the following code cells? It doesn't have to be more than a few words, but someone should be able to read your comments and understand what the code will do without looking at the code.

**Comment by bsipocz** [comment]
@bmorris3 @kvyh - I wonder whether the ``astroplan/tests`` are the best place for tutorial like notebooks? What about adding those examples to the narrative docs and/or having them as a sphinx-gallery or move to the tutorials?

Also this PR adds output, including figures to the currently existing s4 notebook. I think even if the notebooks are decided to be kept, the outputs should be consistent, either being cleared or be there for all the notebooks.

**Comment by wtgee** [comment]
Regarding notebooks, `examples/notebooks` is a standard place I would like to see them go. :)

**Comment by bsipocz** [comment]
Independently of the location I think they should be move out of the repo unless they are being CI tested. Having the odd broken notebooks around can be a headache to deal with maintenance wise. Sphinx gallery is already been set up and working nicely for core, what about using it here, too?

**Comment by bmorris3** [comment]
@bsipocz @wtgee The notebooks are in the tests dir right now only because we're experimenting with the scheduling API, and want to be able to exchange an example notebook for dev purposes, not for tutorial purposes. 

The next task that @kvyh will be taking on will be designing narrative docs for the RTD page, which will explain how to use the scheduling module and replace these dev notebooks.

**Comment by bmorris3** [comment]
Merging, with the caveat that tutorials in notebooks get removed, and re-implemented as tutorials in the docs. I've made an issue (#200) to make sure we keep track of that task. 

Thanks @kvyh!

**Pull request merged**
