### PR TITLE
Travis updates

### PR DESCRIPTION
**Pull request by wtgee**
* Make astropy 1.2 the default test version
* Allow for failures on numpy dev and astropy 1.3 until they are supported

### CODE REVIEW

**Comment by wtgee** [comment]
This is failing because of incompatible conda requirements as discussed in OpenAstronomy/conda-channel#9. To some extent I think that if we are assuming the user is running conda to user the module then we can assume they will meet those requirements. Then again, that might not be a realistic requirement for some.

(Note that two tests fail because of small doc errors as per #279)

**Comment by bsipocz** [comment]
@wtgee - To allow a build to fail you should not remove it from the main matrix, but repeat it under allow_failure. 

Also I'm 👎 for allowing astropy stable tests to fail, that would only create an illusion, experience shows (not just here, but with other packages) that builds in that section get ignored rather than fixed.

**Comment by wtgee** [comment]
Thanks @bsipocz, I didn't know that about the build matrix.

I guess my thinking at this point was that astropy stable is not supported and the tests should reflect that until it is officially supported otherwise every single PR is going to have a whole bunch of failures, which makes everything else hard to test. If the number one priority is to get astropy stable supported as soon as possible I think it would be fine to keep it required but I think that would then need to be a high priority. Since `astroplan` doesn't see a lot of movement on the outstanding PRs I think it just creates a hassle for anyone trying to submit PRs when they have to deal with a whole bunch of failing tests that they can't possibly resolve.

I agree with you that builds just get ignored if they are allowed to fail but in this case it seems like certain people (namely you :smile:) would be working on making those builds successful with the idea of making them required tests when astropy stable is supported. I'm happy to close the PR though and leave the travis configs up to those in charge.

**Comment by bsipocz** [comment]
@wtgee - I don't know much about the official priorities, @bmorris3 or @eteq should have all the insights. The branch I mentioned to collect the fixes from the various PRs is this one: https://github.com/bsipocz/astroplan/tree/wip_test_branch and travis is run on it on my fork: https://travis-ci.org/bsipocz/astroplan/. You're right that at the moment it looks hopeless, but I'm certain that most (maybe all?) of the failures are due to two issues only.

**Comment by wtgee** [comment]
Thanks @bsipocz! I'm going to close this for now.

**Pull request closed without merging**
