### PR TITLE
LocalTimeConstraint fixed timezone (#466)

### PR DESCRIPTION
**Pull request by Lagrang3**
Constraint objects are fed an 'astropy.time.Time' variable.
LocalTimeConstraint must transform that time according
to the local time-zone.

### CODE REVIEW

**Comment by wtgee** [comment]
Hi @Lagrang3, you've mixed two PRs here by merging the `plot_sky_error` branch into this.  I realize this was probably just so you can make your system work, but let's keep them isolated until they are merged.  Can you remove the label appending for the sky plots in this PR?

**Comment by Lagrang3** [comment]
> Hi @Lagrang3, you've mixed two PRs here by merging the `plot_sky_error` branch into this. I realize this was probably just so you can make your system work, but let's keep them isolated until they are merged. Can you remove the label appending for the sky plots in this PR?

Oh, I see. I thought PR where based on commits not on branches. I will then create a new branch for this fix.

**Comment by wtgee** [comment]
> Oh, I see. I thought PR where based on commits not on branches. I will then create a new branch for this fix.

This is true. But you've merged the commit into the branch so it's now part of that branch. It's a "organizational" and "logical" issue, not a git issue. It would handle the merge just fine in the end, you just want to keep the features/fixes isolated while being developed.

**Comment by Lagrang3** [comment]
Should I then make a new PR with a dedicated branch?

**Pull request closed without merging**
