### PR TITLE
Updating astropy_helpers to 2.0.8

### PR DESCRIPTION
**Pull request by bsipocz**
~Do not merge yet, it's opened for testing and needs to be updated to point to the actual release when it's released.~

This now points to the release, merge when passes.

### CODE REVIEW

**Comment by bsipocz** [comment]
I'm not exactly sure what goes on here. Now more test are failing than before, but it's almost certain to be unrelated to this PR.

**Comment by bmorris3** [comment]
@bsipocz I restarted the Travis jobs and they passed – can you do the same for AppVeyor?

**Comment by bsipocz** [comment]
Done. Please merge away once it passes, so I can start off the helpers update for the rest of the packages tonight (would avoid doing it while this is open as I was inconsistent with naming the branch, so it would open another update here...)

**Comment by bmorris3** [comment]
@bsipocz I don't understand why but it failed.

**Comment by bsipocz** [comment]
Yeah, weird.  Given it's windows python2, I don't really have the means to investigate.

**Comment by bmorris3** [comment]
Me neither, not sure what to do.

**Comment by bsipocz** [comment]
drop python2 :trollface:

**Comment by bmorris3** [comment]
How would you feel about merging and seeing if that build passes, and if it doesn't, then we drop Windows py2?

**Comment by bsipocz** [comment]
I always feel great when it's about withdrawing support for python2 :)

**Comment by bmorris3** [comment]
Ok, merging and hoping for the best.

**Pull request merged**
