### PR TITLE
Removing the astroplan sites module (which migrated to astropy)

### LINKED ISSUE #121: Update Observer.at_site to use astropy site machinery
astropy/astropy#4042 is now merged, so it probably makes sense to switch to that in favor of the astroplan `get_site` machinery.

To clarify one additional thing about this: I think it may make sense for the data.astropy.org/coordinates/sites.json file to get *additional* information down the road about sites.  That info may be used by astroplan even if its ignored by astropy itself.  So no need to worry that it's now "out of astroplan's control": astropy-data is an easy thing to change!  I don't *think* that's particularly relevant right now, but it might be if more information gets added to `Observer` that's not in `EarthLocation` but should be in the data file.

### PR DESCRIPTION
**Pull request by bmorris3**
The astroplan `sites` module was added in #45, and then ported to astropy in astropy/astropy#4042. Since then, we've been meaning to remove the now redundant sites machinery from astroplan. In this PR, I removed the sites module and associated tests. 

In addition, I had to create a new monkey patch. Many of the tests for the `astroplan.Observer` class used the class method `astroplan.Observer.at_site` to efficiently resolve coordinates for an observatory with the original sites module. Since the original sites module had a local copy of the site database stored offline, the tests written with `astroplan.Observer.at_site` would function identically in tests with or without the `--remote-data` flag. Now that we're using `EarthLocation.of_site` under the hood which always accesses the internet, I had to monkey-patch the `EarthLocation.of_site` method if the `--remote-data` option is not used, so that the tests can still resolve coordinates for the observatories in the tests without internet access.

This closes #121 and #40.

cc @cdeil, my monkey-patch tutor.

### CODE REVIEW

**Comment by bmorris3** [comment]
These tests will fail until we update the required astropy version to >1.1 (I think that's the version with `EarthLocation.of_site`). Since in #167 I raise the requirements to astropy>=1.2, we might as well wait to retest/merge this PR until #167 is merged.

**Comment by cdeil** [comment]
I think it's OK if astroplan 0.2 will require astropy 1.2.

**Comment by bsipocz** [comment]
@bmorris3 - this also closes #119

**Comment by ejeschke** [comment]
It would be nice if `EarthLocation.of_site` in astropy would not have to access the internet every time it is called. Is it not written to use a cache between process invocations, @bmorris3 ?

**Comment by bmorris3** [comment]
@ejeschke – the method caches the observatory database on first access, then accesses the cache each time unless it's forced to re-download, see [source here](https://github.com/astropy/astropy/blob/v1.1.x/astropy/coordinates/earth.py#L258). The monkey patch was needed because the tests would have to access the remote database once in order to download the database.

**Comment by bmorris3** [comment]
With the IERS errors fixed, this is ready for merge.

**Pull request merged**
