### PR TITLE
Updating .travis to reflect recent miniconda changes

### PR DESCRIPTION
**Pull request by bsipocz**
Miniconda's default prefix changed recently causing all travis builds failing.

### CODE REVIEW

**Comment by cdeil** [comment]
@bsipocz - Thanks!

@bmorris3 @eteq - Any idea why these errors show up now?
- https://travis-ci.org/astropy/astroplan/jobs/89301863#L742
- https://travis-ci.org/astropy/astroplan/jobs/89301873#L595
Should be unrelated to this PR, no?

**Comment by bsipocz** [comment]
While I was at it I've updated the helpers, too.

**Comment by bsipocz** [comment]
@cdeil - I see the ``test_sun_separation`` failure locally, too, so that one is unrelated for sure. And two more doctests are failing with remote testing.

**Comment by bsipocz** [comment]
Full log:
```
============================== test session starts ===============================
platform darwin -- Python 2.7.10 -- py-1.4.30 -- pytest-2.7.3
rootdir: /private/var/folders/dc/hsm7tqpx2d57n7vb3k1l81xw0000gq/T/astroplan-test-Aup5Zw, inifile: setup.cfg
plugins: capturelog, cov, html, mpl, selenium, selenium, variables

Running tests with Astropy version 1.1.dev13982.
Running tests in lib.macosx-10.10-x86_64-2.7/astroplan docs.

Date: 2015-11-04T20:34:14

Platform: Darwin-14.5.0-x86_64-i386-64bit

Executable: /Users/bsipocz/.virtualenvs/astropy-dev/bin/python

Full Python Version: 
2.7.10 (default, May 26 2015, 20:29:34) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]

encodings: sys: ascii, locale: UTF-8, filesystem: utf-8, unicode bits: 15
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.10.1
Scipy: 0.16.0
Matplotlib: 1.5.0
astropy: 1.1.dev13982
pytz: 2015.7
pyephem: not available
matplotlib: 1.5.0
nose: 1.3.7
pytest-mpl: not available
Using Astropy options: remote_data.

collected 78 items 

astroplan/constraints.py .
astroplan/observer.py .........FF.....
astroplan/sites.py .
astroplan/target.py ...
astroplan/plots/tests/test_sky.py .
astroplan/tests/test_constraints.py ....Fss...
astroplan/tests/test_moon.py s
astroplan/tests/test_observer.py .....................s...
astroplan/tests/test_sites.py .....
astroplan/tests/test_target.py ..
astroplan/tests/test_utils.py .
../docs/api.rst .
../docs/getting_started.rst .
../docs/index.rst .
../docs/installation.rst .
../docs/faq/contribute.rst .
../docs/faq/iers.rst .
../docs/faq/index.rst .
../docs/faq/precision.rst .
../docs/tutorials/constraints.rst .
../docs/tutorials/index.rst .
../docs/tutorials/plots.rst .
../docs/tutorials/summer_triangle.rst .

==================================== FAILURES ====================================
______________ [doctest] astroplan.observer.Observer.sun_rise_time _______________
732     def _calc_transit(self, time, target, prev_next, antitransit=False, N=150):
733         """
734         Time at next transit of the meridian of `target`.
735 
736         Parameters
737         ----------
738         time : `~astropy.time.Time` or other (see below)
739             Time of observation. This will be passed in as the first argument to
740             the `~astropy.time.Time` initializer, so it can be anything that
741             `~astropy.time.Time` will accept (including a `~astropy.time.Time`
Expected:
    ISO: 2001-02-02 14:02:50.554, JD: 2451943.08531
Got:
    ISO: 2001-02-02 14:04:43.151, JD: 2451943.08661

astroplan/observer.py:741: DocTestFailure
-------------------------------- pytest-selenium ---------------------------------

_______________ [doctest] astroplan.observer.Observer.sun_set_time _______________
732     def _calc_transit(self, time, target, prev_next, antitransit=False, N=150):
733         """
734         Time at next transit of the meridian of `target`.
735 
736         Parameters
737         ----------
738         time : `~astropy.time.Time` or other (see below)
739             Time of observation. This will be passed in as the first argument to
740             the `~astropy.time.Time` initializer, so it can be anything that
741             `~astropy.time.Time` will accept (including a `~astropy.time.Time`
Expected:
    ISO: 2001-02-04 00:35:42.102, JD: 2451944.52479
Got:
    ISO: 2001-02-04 00:38:42.198, JD: 2451944.52688

astroplan/observer.py:741: DocTestFailure
-------------------------------- pytest-selenium ---------------------------------

______________________________ test_sun_separation _______________________________

    def test_sun_separation():
        time = Time('2003-04-05 06:07:08')
        apo = Observer.at_site("APO")
        sun = get_sun(time)
        one_deg_away = SkyCoord(ra=sun.ra, dec=sun.dec+1*u.deg)
        five_deg_away = SkyCoord(ra=sun.ra+5*u.deg, dec=sun.dec)
        twenty_deg_away = SkyCoord(ra=sun.ra+20*u.deg, dec=sun.dec)
    
        constraint = SunSeparationConstraint(min=2*u.deg, max=10*u.deg)
        is_constraint_met = constraint(apo, [one_deg_away, five_deg_away,
                                             twenty_deg_away], times=time)
>       assert np.all(is_constraint_met == [[False], [True], [False]])
E       assert <function all at 0x105f23320>(array([[False...], dtype=bool) == [[False], [True], [False]]
E        +  where <function all at 0x105f23320> = np.all
E         Use -v to get the full diff)

astroplan/tests/test_constraints.py:141: AssertionError
-------------------------------- pytest-selenium ---------------------------------

================ 3 failed, 71 passed, 4 skipped in 45.50 seconds =================
```

**Comment by bmorris3** [comment]
Thanks @bsipocz! I'm taking a look at the `SunSeparationConstraint` error now. 

We're likely going to be hacking on `astroplan` at dotastronomy today, so I'm going to try to take care of this as quickly as possible.

**Comment by bmorris3** [comment]
The build that failed that wasn't a `SunSeparationConstraint` error was a urllib error, it went away when I restarted the test.

**Comment by bmorris3** [comment]
@eteq – the astropy-dev version is causing the `SunSeparationConstraint` to fail. Is it possible that changes to the `GCRS`/other coordinate transformations is causing this?

Here's the [error](https://travis-ci.org/astropy/astroplan/jobs/89301873#L681-L686): 
```
>       assert np.all(is_constraint_met == [[False], [True], [False]])
E       assert <function all at 0x7f5a7fa60488>(array([[False...], dtype=bool) == [[False], [True], [False]]
E        +  where <function all at 0x7f5a7fa60488> = np.all
E         Full diff:
E         + [[False], [True], [False]]
E         - array([[False],
E         -        [False],
E         -        [False]], dtype=bool))
astroplan/tests/test_constraints.py:141: AssertionError
=============== 3 failed, 68 passed, 6 skipped in 40.38 seconds ================
The command "if [[ $MAIN_CMD == 'python setup.py' ]]; then $MAIN_CMD $SETUP_CMD; fi" exited with 1.
```

**Comment by cdeil** [comment]
Merging this now (the remaining issue with SunSeparationConstraint is unrelated).

**Comment by eteq** [comment]
@cdeil @bmorris3 - I think I understand the source of this - as you guessed, @bmorris3, it's due to the recent changes in astropy, but in a somewhat subtle way.  See #138 to track this more.

**Pull request merged**
