### PR TITLE
Adding build with numpy pre-release to the travis matrix

### PR DESCRIPTION
**Pull request by bsipocz**
~~and updates astropy-helpers to v1.1.1~~

[Edit]: updates the helpers to v1.2rc1 and closes #162

### CODE REVIEW

**Comment by bmorris3** [comment]
It looks like something in the Sphinx build is failing for only Python 3: [see here](https://travis-ci.org/astropy/astroplan/jobs/113019645#L843)

**Comment by bsipocz** [comment]
This is an issue with astropy-helpers since v1.1rc2, we saw the same with gammapy https://github.com/gammapy/gammapy/pull/462#issuecomment-187671120. 
Basically all non strictly sphinx warnings are fail the build started with ``-w``. One can argue that this is a good thing, however I'm not 100% sure about it, it caused more issues that are untrivial to solve.

cc @cdeil @eteq for the discussion, maybe this is something we should revoke from the helpers? Or introduce a new flag like ``-ww`` to catch these as well?

The task is really to get rid of these warnings:
```
WARNING: Tried to get polar motions for times after IERS data is valid. Defaulting to polar motion from the 50-yr mean for those.

If you need enough precision such that this matters (~<10 arcsec), you can

download the latest IERS predictions by running:

    >>> from astropy.utils.data import download_file

    >>> from astropy.utils import iers

    >>> iers.IERS.iers_table = iers.IERS_A.open(download_file(iers.IERS_A_URL, cache=True))
```

**Comment by bsipocz** [comment]
Rebased.

**Comment by bsipocz** [comment]
Ohh, a somewhat related question: do you what to test against the RC astropy version? 

I don't think it's very practical though as astropy has a prerelease version only for a very short time that may not overlap with an active development time for astroplan. When there is no rc available the build shows a pass.

**Comment by bsipocz** [comment]
@bmorris3 - It looks like there may be another example where the iers warnings are triggered, however this build will pass once the new 1.2 helpers are in.

**Comment by bsipocz** [comment]
Updated the helpers to be v1.2rc1, this should do the trick I think.

**Comment by bmorris3** [comment]
Thanks @bsipocz! I want to double check – is this OK to merge before #162?

**Comment by bsipocz** [comment]
@bmorris3 - This overrides #162 as includes the newer (yet unreleased) helpers. Yet I think it's OK to update to that version now, as there won't be an astroplan release before the new official 1.2 helpers.

**Comment by bmorris3** [comment]
Thanks for the explanation. I'll merge this one and close #162.

**Pull request merged**
