### PR TITLE
Moving methods to the base `Scheduler` class

### PR DESCRIPTION
**Pull request by wtgee**
Mostly just cleanup code as per #206

### CODE REVIEW

**Comment by bmorris3** [comment]
This looks good. @kvyh – will this affect all of your PRs? I think you'll have to rebase, and I want to merge this at a time that's convenient for everyone.

**Comment by wtgee** [comment]
@bmorris3 @kvyh I was just about to move the `__init__` into this same branch (and rename this pull-request). Do you want a separate branch for that? They are both just moving things to the base so I figured the same would be ok.

**Comment by kvyh** [comment]
This shouldn't affect any of my PRs, none of them currently deal with the initialisation of the `schedulers`.

**Comment by bmorris3** [comment]
Looks good @wtgee, thanks! @kvyh – be advised that you'll need to rebase your scheduler PRs. And the `Schedule` implementation discussed in #209, #217 [is now condensed into this line.](https://github.com/astropy/astroplan/pull/207/files#diff-c5817539e1e3659676472222fb270326R381)

**Pull request merged**
