### PR TITLE
Update astropy-helpers to v1.1.2

### PR DESCRIPTION
**Pull request by astrofrog**
This is an automated update of the astropy-helpers submodule to v1.1.2. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed.

*This is intended to be helpful, but if you would prefer to manage these updates yourself, or if you notice any issues with this automated update, please let @astrofrog know!*

### CODE REVIEW

**Comment by bsipocz** [comment]
The sphinx build issue (where the build is failing due to upstream warning and not because of sphinx warnings) will be solved I think with the new astropy-helpers release, that includes the fix of https://github.com/astropy/astropy-helpers/pull/223

The other failure looks real though but unrelated to the changes here.

**Comment by bmorris3** [comment]
This failure seems to be stemming from the plotting tutorials, which use a time in 2015. That recent date triggers an IERS update, which raises a warning. I'm going to see if changing all 2015 dates to 2000 will fix this error.

**Comment by bmorris3** [comment]
@bsipocz I'm very confused and I wonder if you could help? I thought I had a possible solution in #169, which passed, but when I re-ran the travis test that is failing, it did not succeed. What's going on?

**Comment by bsipocz** [comment]
@bmorris3 - This needs to be rebased to include those changes you made in #169.

**Comment by bsipocz** [comment]
(looking at it, I can rebase #148 that also includes the helpers update).

**Pull request closed without merging**
