### PR TITLE
Small correction in observer.py and Scheduling doc 

### PR DESCRIPTION
**Pull request by lordaniket06**

### CODE REVIEW

**Comment by StuartLittlefair** [comment]
Failures are related to the issues resolved in #295. Should pass once that is merged, and upstream fix is in place in astropy.

**Comment by lordaniket06** [comment]
@bmorris3 , @StuartLittlefair any idea why the build is failing, Apparently the correction in the scheduling doc is causing the problem. In the first commit, I removed the import of `Isiterable` module which is successfully passing the build test.
  On the other hand , a simple typo correction causes the build to fail?

**Comment by lordaniket06** [comment]
Shall I open another PR just for the [removal of module].(https://github.com/astropy/astroplan/pull/293/commits/7ceaa36e6340a5aa91d36e0e758e85be1dfb89c7)

**Comment by bsipocz** [comment]
@lordaniket06 - No, fixing a typo doesn't break the tests. The travis failures are unrelated and everything should be passing again once #295 is merged.

**Comment by lordaniket06** [comment]
Okay. Though #295 has been open for a while. Is there any other pertaining problem due to which it isn't merged yet?

**Comment by bmorris3** [comment]
Thanks @lordaniket06.

**Pull request merged**
