### PR TITLE
Support Numpy 1.x and 2.x

### PR DESCRIPTION
**Pull request by lpsinger**
This reverts commit df7f1d39679581fe58c8eaf9201adc0df2bade57.

### CODE REVIEW

**Comment by lpsinger** [comment]
@bmorris3, would you please take a look at this? I've updated most of the codes that I maintain to support Numpy 2.x, and Astroplan is one of the few dependencies of my projects that does not yet support it.

**Comment by bmorris3** [comment]
Thank you @lpsinger! Sorry I missed this PR!

**Comment by lpsinger** [comment]
Would you please do a release to pick up this patch?

**Comment by bmorris3** [comment]
Done! https://pypi.org/project/astroplan/0.10.1/

**Comment by lpsinger** [comment]
Yay, thank you!

**Pull request merged**
