### PR TITLE
Adding requested plot_sky_24hr [#51]

### PR DESCRIPTION
**Pull request by bmorris3**
Here's a new method for `astroplan.plots` that plots a target's position as it moves through the sky over the course of 24 hours, requested in #51. Here's an example:
```python
from astroplan.plots import plot_sky_24hr
from astropy.time import Time
import astropy.units as u
from astroplan import Observer, FixedTarget
import matplotlib.pyplot as plt

vega = FixedTarget.from_name('Vega')
apo = Observer.at_site('APO')
kwargs_at_center_time = {'color': 'r', 'marker': 's', 's': 100}
plot_sky_24hr(vega, apo, Time.now(), delta=1*u.hour,
              center_time_style_kwargs=kwargs_at_center_time)
plt.show()
```
figure_1

I also added a new kwarg to `plot_sky` called `warn_below_horizon` which toggles the warning that comes up when a user tries to plot the position of a target that's below the horizon. This warning isn't useful when `plot_sky` is called via `plot_sky_24hr`, so `plot_sky_24hr` shuts off the warning. 

cc @jberlanga

### CODE REVIEW

**Comment by ejeschke** [comment]
Nice, thank you!

**Comment by bmorris3** [comment]
@ejeschke - did/would you review the pull request?

**Comment by ejeschke** [comment]
@bmorris3, it looks good to me.  I don't see a test in this PR.  Maybe one could be added similar to what is being considered for the other plots?

**Comment by bmorris3** [comment]
The other plots aren't currently being tested (see [cdeil's comment](https://github.com/astropy/astroplan/pull/115#issuecomment-143801514) in #115). There are some issues in the plot testing machinery that are being worked out before we implement tests (see astrofrog/pytest-mpl#12).

**Pull request merged**
