### PR TITLE
Changing pytest import to use astropy bundled

### PR DESCRIPTION
**Pull request by bsipocz**
To be more consistent, and hopefully to solve @wtgee's https://github.com/astropy/astropy/issues/5202 issue.

### CODE REVIEW

**Comment by bsipocz** [comment]
Same random fail we saw yesterday. The build needs a restart and then should pass.

**Comment by StuartLittlefair** [comment]
@bsipocz I think you can restart builds yourself by closing and then re-opening the PR

**Comment by bsipocz** [comment]
Yes, but it triggers the whole travis run which is a waste of CI resources as only one build was failing (and since we saw the very same yesterday, I'm sure this can even be merged without it and will get the all green).

**Comment by bmorris3** [comment]
@bsipocz Restarting that one test now just to be safe.

**Comment by bmorris3** [comment]
Passing. Thanks @bsipocz. Should be good now @wtgee.

**Comment by wtgee** [comment]
Thanks all. I'm still having same issues with astropy but will move it over to astropy/astropy#5202

**Comment by wtgee** [comment]
Ok, still trying to figure this out and I'm not sure the problem is on astropy side. I created a completely clean fork of astroplan where the only change is to try and print the value of `remote_data` before passing the `config` to the associated astropy test.  Lines added here:

https://github.com/wtgee/astroplan/blob/test-conftest/astroplan/conftest.py#L53

Using this fork in my travis-ci build fails on the print line, here:

https://travis-ci.org/panoptes/POCS/jobs/148198413#L832

Same error, just before passing to the astropy tests. How/where/why do I get this remote_data value to show up?

**Comment by wtgee** [comment]
Ok, I have a different repo that has almost nothing in it. I have one simple test and very minimal requirements. It is building fine and passing the tests in travis. If I add astroplan to my `.travis.yml` file (cloning from repo then installing) I get the `remote_data` error. I can open a new Issue for this rather than hash it out here.

https://travis-ci.org/panoptes/PIAA/jobs/148232555

**Comment by bmorris3** [comment]
@wtgee I haven't been in the loop on all of your debugging efforts, and I'm pretty sure this is unrelated, but small heads up: we've moved astroplan's `--remote-data` tests into the allowed failures section of our testing matrix because of difficulties with IERS warnings. 

It looks like there's something else going on in that build log, though. This is one where I would rely on @bsipocz's wizardry.

**Comment by bsipocz** [comment]
@bmorris3 - Yep, it's fixed now in a pending PR to POCS.

**Comment by wtgee** [comment]
Thanks @bmorris3 for the update and much thanks to @bsipocz for the magical incantations!

**Pull request merged**
