### PR TITLE
Adding nitpicky option

### PR DESCRIPTION
**Pull request by bsipocz**
I think the nitpicky option should be turned on sooner rather than later. Right now there are about ~100 broken links already in the docs. 
If you prefer I can try to fix them during the slightly toxicated sprint moments this week ;)

### CODE REVIEW

**Comment by cdeil** [comment]
@bsipocz – If you can clean up those warnings, that would be great!

Today is probably not a good time though ... there's a few PRs on the docs already in progress that will get merged later today.

**Comment by bsipocz** [comment]
OK. After the PR's are merged I'll clean it up during the weekend. It's
getting late anyway, and I'm already in the deepest of multitasking...

**Comment by bsipocz** [comment]
@cdeil - would you ping me on this once you merge the those PRs you mentioned above? Then I'll try to do this before you release.

**Comment by cdeil** [comment]
The other PRs you should wait for is mainly #77  and probably also #79.
I'll ping you here once they are in.

**Comment by eteq** [comment]
@bsipocz - the two PRs @cdeil mentioned are done... But #87 now also touches some of the docs.  It *may* not conflict with what you're planning here, though, because #87 is mostly touching code blocks rather than narrative docs (where you are likely to find most of the links).

**Comment by cdeil** [comment]
@bsipocz - Thanks for doing this.

There's some nitpicky warnings left that make the travis-ci build fail:
https://travis-ci.org/astropy/astroplan/jobs/78436519#L746

@bmorris3 as 0.1 release manager – This is currently labeled 0.1, but IMO can go in 0.2 if you want to cut the release today.
(There will likely be other things we miss and new features soon, so we can release 0.2 in a few weeks if we like.)

**Comment by bsipocz** [comment]
@cdeil - yes I know, but wanted to commit the stuff I had before leaving
the office (also to see what's is still missing as my local build is having
some SSL issues).

**Comment by bmorris3** [comment]
@bsipocz Thanks for this! I've moved this to 0.2 so this doesn't block 0.1.

**Comment by bsipocz** [comment]
@bmorris3 - sure. 

FYI: I've temporarily disabled most of the travis builds, since as I mentioned my local has a mess up. If I manage to get a pass on it tonight, I'll ping you.

**Comment by bsipocz** [comment]
@bmorris3 - This should pass now.

**Comment by cdeil** [comment]
Travis-ci tests passed.
:+1:  to merge.
Thanks!

This might conflict with #87, so whichever is merged first, the other might have to be rebased.

**Comment by bmorris3** [comment]
Especially after #92 has been merged, this will need a rebase. Sorry for the extra work @bsipocz!

**Comment by bsipocz** [comment]
Rebased, and travis runs passed (This latest one can be cancelled if you like, as the only difference is that I've rebased it again to remove the temporary minimization of the travis matrix)

**Comment by bsipocz** [comment]
@eteq - I've included the new ``AstroplanWarning`` class in the public API, thus the other warning classes can resolve its link for their baseclass. Hope you don't mind.

**Comment by bmorris3** [comment]
@bsipocz: Beautiful! Looks good, merging.

**Pull request merged**
